{{- $gensim := index .Values "general-simulation" | default dict -}}
{{- if $gensim.enabled }}
{{- $neo4jSa := "neo4j-sa" -}}
{{- with $gensim.neo4j -}}
{{- with .podSpec -}}
{{- if eq .serviceAccountName "" -}}
{{- $neo4jSa = "" -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if $neo4jSa }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $neo4jSa }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
