FROM python:3.12-slim

RUN useradd -m appuser

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    rm -rf /root/.cache

COPY . ./

RUN chown -R appuser:0 /app && chmod -R g+rwX /app
USER appuser

CMD ["python", "main.py"]
